server:
  port: 28090
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/chanygram?serverTimezone=Asia/Seoul
    username: chany
    password: chany1234

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.default_batch_fetch_size: 1000

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB

  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 541312677464433
            client-secret: 6db0ebbd263a19c4463a5de8a9dfd545
            scope:
              - public_profile
              - email

custom:
  file:
    path: E:/data/upload/

  story:
    page-size: 6